// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("kibana")]
[assembly: AssemblyDescriptionAttribute("kibana")]
[assembly: GuidAttribute("ffb9da32-12fa-4c9d-a5bd-06cddae74fd4")]
[assembly: AssemblyProductAttribute("Kibana")]
[assembly: AssemblyMetadataAttribute("GitBuildHash","44ab5e")]
[assembly: AssemblyCompanyAttribute("Elasticsearch BV")]
[assembly: AssemblyCopyrightAttribute("Apache License, version 2 (ALv2). Copyright Elasticsearch.")]
[assembly: AssemblyTrademarkAttribute("Kibana is a trademark of Elasticsearch BV, registered in the U.S. and in other countries.")]
[assembly: AssemblyVersionAttribute("5.5.1")]
[assembly: AssemblyFileVersionAttribute("5.5.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "kibana";
        internal const System.String AssemblyDescription = "kibana";
        internal const System.String Guid = "ffb9da32-12fa-4c9d-a5bd-06cddae74fd4";
        internal const System.String AssemblyProduct = "Kibana";
        internal const System.String AssemblyMetadata_GitBuildHash = "44ab5e";
        internal const System.String AssemblyCompany = "Elasticsearch BV";
        internal const System.String AssemblyCopyright = "Apache License, version 2 (ALv2). Copyright Elasticsearch.";
        internal const System.String AssemblyTrademark = "Kibana is a trademark of Elasticsearch BV, registered in the U.S. and in other countries.";
        internal const System.String AssemblyVersion = "5.5.1";
        internal const System.String AssemblyFileVersion = "5.5.1";
    }
}
